name: Test Authentication Flow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Setup D1 Database
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        command: d1 execute auth-db --local --file=./schema.sql
      
    - name: Run tests
      run: npm test
      env:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
        CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
        NEXT_PUBLIC_CLERK_SIGN_IN_URL: '/sign-in'
        NEXT_PUBLIC_CLERK_SIGN_UP_URL: '/sign-up'
        NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: '/members'
        NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: '/members'
        JWT_SECRET: ${{ secrets.JWT_SECRET }} 